version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cipherchest-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./attachments:/app/attachments
      - ./backups:/app/backups
      - ./data:/app/data
    networks:
      - cipherchest-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cipherchest-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cipherchest-network

networks:
  cipherchest-network:
    driver: bridge
